SET search_path TO NOTIFICATIONS;

-- DROP TRIGGER BEFORE INSERTING
  BEGIN TRANSACTION;
DROP TRIGGER SIMPLE_NOTIFICATIONS_NOTIFY ON SIMPLE_NOTIFICATIONS;
-- DO A CLEANUP
DELETE FROM SIMPLE_NOTIFICATIONS;
-- INSERT DATA
CREATE OR REPLACE FUNCTION INSERT_MASSIVE_DATA(INTEGER) RETURNS VOID AS $$
DECLARE
    loops ALIAS FOR $1;
BEGIN
    RAISE INFO 'INSERTING DATA %', loops;
    RAISE INFO 'Start timestamp: %', timeofday()::TIMESTAMP;
    FOR i IN 1..loops LOOP
        INSERT INTO NOTIFICATIONS.SIMPLE_NOTIFICATIONS(message) VALUES ('a');
    END LOOP;
    RAISE INFO 'end of inserting timestamp: %', timeofday()::TIMESTAMP;
END;
$$ LANGUAGE 'plpgsql' STRICT;

SELECT INSERT_MASSIVE_DATA(10000);
-- RECREATE TRIGGER
CREATE TRIGGER SIMPLE_NOTIFICATIONS_NOTIFY
  AFTER INSERT OR UPDATE OR DELETE
  ON SIMPLE_NOTIFICATIONS
  FOR EACH ROW
  EXECUTE PROCEDURE SIMPLE_NOTIFICATIONS_NOTIFY();
COMMIT;

BEGIN TRANSACTION;
 UPDATE  SIMPLE_NOTIFICATIONS SET db_creation = statement_timestamp();
COMMIT;
